name: $(Date:yyyyMMdd)$(Rev:.r)
variables:
  var1: value1
jobs:
- job: One
  steps:
  - script: echo First step!
trigger:
  batch: true
  branches:
    include:
    - master/*
    exclude:
    - master/experimental/*
  paths:
    exclude:
    - README.md
